name: Expose Outline Wiki via Serveo

on:
  workflow_dispatch:

jobs:
  expose-ports:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y curl jq socat openssh-server python3-pip openssh-client

      - name: Start SSH server
        run: |
          sudo service ssh start
          echo "root:Docker!" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Run Outline container
        run: docker run -d --name outline -p 8090:3000 outlinewiki/outline

      - name: Start Serveo tunnel (expose port 8090)
        run: |
          nohup ssh -o StrictHostKeyChecking=no -R 80:localhost:8090 serveo.net > serveo.log 2>&1 &

      - name: Show Serveo public URL
        run: |
          sleep 8
          head -n 20 serveo.log

      - name: Keep job alive to keep tunnel and ssh running
        run: |
          echo "Tunnel and SSH server are running. SSH with root/Docker! on this machine."
          tail -f serveo.log
