name: SSH to GitHub Actions VM

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 */5 * * *" # Runs every 5 hours to auto-restart

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart
          echo "root:github" | sudo chpasswd  # Set root password

      - name: Start SSH Tunnel via Serveo
        run: |
          ssh -o StrictHostKeyChecking=no -R 0:localhost:22 serveo.net > serveo.txt 2>&1 &
          sleep 5
          grep -oE "serveo.net:[0-9]+" serveo.txt | tee ssh_port.txt
          echo "Now SSH into the VM using:"
          cat ssh_port.txt | sed 's/^/ssh -p /;s/$/ root@serveo.net/'

      - name: Keep VM Alive
        run: sleep 17999
