name: SSH to GitHub Actions VM

on:
  workflow_dispatch: # Trigger manually

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PermitEmptyPasswords no" | sudo tee -a /etc/ssh/sshd_config
          echo "root:github" | sudo chpasswd
          sudo systemctl restart ssh

      - name: Download Cloudflared
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared

      - name: Start Cloudflare Tunnel
        run: |
          echo "Starting Cloudflare Tunnel..."
          cloudflared tunnel --url ssh://localhost:22 --no-autoupdate > cf.log 2>&1 &

          echo "Waiting for Cloudflare tunnel to be ready..."
          sleep 15

          CF_URL=$(grep -oE "https://[a-zA-Z0-9.-]+\.trycloudflare\.com" cf.log | head -n 1)
          if [[ -z "$CF_URL" ]]; then
            echo "Failed to retrieve Cloudflare URL"
            cat cf.log
            exit 1
          fi

          echo "✅ SSH Tunnel Ready!"
          echo "🌐 Tunnel URL: $CF_URL"
          echo "🔑 Login using:"
          echo "------------------------------------------------------"
          echo "ssh -o ProxyCommand=\"cloudflared access ssh --hostname ${CF_URL/https:\/\//}\" root@localhost"
          echo "------------------------------------------------------"

      - name: Keep VM Alive
        run: sleep infinity
