name: SSH to GitHub Actions VM

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 */5 * * *" # Runs every 5 hours to auto-restart

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart
          echo "root:github" | sudo chpasswd  # Set root password

      - name: Install & Authenticate ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok config add-authtoken 2tbyFMZTbGsnyrIiwkkFRe4daED_5qN5HnVvHt6oC4cLb44nj

      - name: Start SSH Tunnel via ngrok
        run: |
          echo "Starting ngrok tunnel..."
          ngrok tcp 22 > ngrok.log 2>&1 &
          sleep 10  # Ensure ngrok has time to initialize
          
          # Retry fetching the ngrok public URL
          NGROK_URL=""
          for i in {1..10}; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$NGROK_URL" != "null" && "$NGROK_URL" != "" ]]; then
              break
            fi
            echo "Retrying to fetch ngrok URL ($i/10)..."
            sleep 2
          done

          if [[ "$NGROK_URL" == "null" || "$NGROK_URL" == "" ]]; then
            echo "Error: Failed to retrieve ngrok URL"
            cat ngrok.log
            exit 1
          fi

          echo "SSH Tunnel Ready!"
          SSH_CMD=$(echo $NGROK_URL | sed 's/tcp:\/\//ssh root@/;s/:/ -p /')
          echo "Use this command to SSH into the VM:"
          echo "------------------------------------------------------"
          echo $SSH_CMD
          echo "------------------------------------------------------"
