name: SSH to GitHub Actions VM

on:
  workflow_dispatch:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart
          echo "root:github" | sudo chpasswd  # Set root password

      - name: Start SSH Tunnel via Serveo
        run: |
          ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 serveo.net &
          sleep 5
          echo "Now SSH into the VM using:"
          echo "ssh -p 2222 root@serveo.net"

      - name: Keep VM Alive
        run: sleep 17999
